#!/bin/sh

username=$(whoami)

cd /home/$username

git clone https://aur.archlinux.org/paru-bin
cd paru-bin
makepkg -si

packages="https://github.com/DemonKingSwarn/archinstall/raw/master/pkgs.txt"
cd /home/$username
curl -sLo pkgs.txt $packages
while read p; do
    paru -S $p --noconfirm
done < /home/$username/pkgs.txt

echo "Installing advanced cp and mv"
git clone https://github.com/jarun/advcpmv
cd ./advcpmv
sh ./install.sh
sudo mv ./advcp /usr/local/bin/cpg
sudo mv ./advmv /usr/local/bin/mvg

cd /home/$username
mkdir .config
mkdir -p .local/bin
mkdir -p .local/share
mkdir -p .local/state/zsh
touch .local/state/zsh/history
mkdir -p .local/lib
git clone https://github.com/demonkingswarn/dotfiles.git .dots
cd .dots
stow --ignore=.git .

cd /home/$username
git clone https://github.com/demonkingswarn/scripts.git .scripts

mkdir -p hdd/pix/
git clone https://github.com/demonkingswarn/wallpapers.git hdd/pix/wall

cd /home/$username/.config
sudo cp env /etc/zsh/zshenv

chsh -s $(which zsh)

echo "run 'exit'"
echo "run 'exit'"
echo "run 'umount -l /mnt'"
echo "run 'reboot'"
