#!/bin/sh

username=$(whoami)

cd /home/$username

packages="https://github.com/DemonKingSwarn/archinstall/raw/master/pkgs.txt"
cd /home/$username
sudo pacman -S paru --noconfirm
curl -sLo pkgs.txt $packages
while read p; do
    paru -S $p --noconfirm
done < /home/$username/pkgs.txt

sudo pacman -S --noconfirm --needed intel-ucode
proc_ucode=intel-ucode.img

sudo pacman -S --noconfirm --needed nvidia-open nvidia-prime nvidia-settings nvidia-utils

echo "Installing advanced cp and mv"
git clone https://github.com/jarun/advcpmv
cd ./advcpmv
sh ./install.sh
sudo mv ./advcp /usr/local/bin/cpg
sudo mv ./advmv /usr/local/bin/mvg

cd /home/$username
mkdir .config
mkdir -p .local/bin
mkdir -p .local/share
mkdir -p .local/state/zsh
touch .local/state/zsh/history
mkdir -p .local/lib
git clone https://github.com/demonkingswarn/dotfiles.git .dots
cd .dots
rm ~/.bashrc
stow --ignore=.git --ignore=README.md --ignore=pkgs.txt --ignore=README.org .

cd /home/$username
mkdir -p .local/share/zsh/plugins && cd .local/share/zsh/plugins
git clone --depth 1 https://github.com/zsh-users/zsh-syntax-highlighting
git clone --depth 1 https://github.com/Aloxaf/fzf-tab

cd /home/$username
git clone --depth 1 https://github.com/demonkingswarn/scripts.git .scripts

mkdir -p $HOME/pix/
git clone --depth 1 https://github.com/demonkingswarn/wallpapers.git $HOME/pix/wall

cd /home/$username/.config
sudo cp env /etc/zsh/zshenv

chsh -s $(which zsh)

echo "run 'exit'"
echo "run 'exit'"
echo "run 'umount -l /mnt'"
echo "run 'reboot'"
