#!/bin/sh

ln -sf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime

hwclock --systohc

echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
locale-gen

printf "Enter the hostname: " && read hostname
echo "$hostname" > /etc/hostname

echo "127.0.0.1     localhost" >> /etc/hosts
echo "::1           localhost" >> /etc/hosts
echo "127.0.1.1     $hostname.localdomain   $hostname" >> /etc/hosts

echo "Set the root password"
passwd

printf "Enter the username: " && read username
useradd -m $username
echo "Enter your $username's password: "
passwd $username

echo "Adding $username into some important groups"
usermod -aG wheel,audio,video,optical,storage $username

pacman -S opendoas which dash --noconfirm
echo "permit persist $username as root" > /etc/doas.conf
ln -s $(which doas) /bin/sudo
ln -s $(which dash) /bin/sh

echo "[multilib]" >> /etc/pacman.conf
echo "Include = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf

pacman -Syyu
pacman -S networkmanager efibootmgr dosfstools os-prober mtools --noconfirm

lsblk
printf "Enter the boot partition (only name, ex: sda1) : " && read bootDrive

printf "Select the bootloader you want:\n1. systemd-boot\n2. grub\n: " && read bootloader

case $bootloader in
    1)
        mount /dev/$bootDrive /boot
        lsblk
        printf "Enter the main partion: (ex: sda3) " && linuxPart
        bootctl --path=/boot install
        echo "timeout 3" > /boot/loader/loader.conf
        echo "default arch-*" >> /boot/loader/loader.conf
        echo "title $hostname" > /boot/loader/entries/arch.conf
        echo "linux /boot/vmlinuz-linux" >> /boot/loader/entries/arch.conf
        echo "initrd    /boot/initramfs-linux.img" >> /boot/loader/entries/arch.conf
        echo "options   root=/dev/$linuxPart rw" >> /boot/loader/entries/arch.conf
        pacman -S linux
        ;;
    2)
        pacman -S grub
        mkdir /boot/EFI
        mount /dev/$bootDrive /boot/EFI
        echo "GRUB_DISABLE_OS_PROBER=false" >> /etc/default/grub
        grub-install --target=x86_64-efi --bootloader-id=grub_uefi --recheck
        grub-mkconfig -o /boot/grub/grub.cfg
        ;;

    *)
        printf "Nothing selected\n"
        exit 1
esac

systemctl enable NetworkManager
systemctl start NetworkManager

pacman -S git fakeroot --noconfirm

pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com
pacman-key --lsign-key 3056513887B78AEB
pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'

echo "[chaotic-aur]" >> /etc/pacman.conf
echo "Include = /etc/pacman.d/chaotic-mirrorlist" >> /etc/pacman.conf

pacman -Syyu

chown $username:$username ./postpost
mv ./postpost /home/$username
echo "run 'cd && ./postpost'"
su $username
